name: test
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
